
development:
    adapter: postgresql
    host: localhost
    database: pintrest_development
    username: postgres
    password: cuelinks
    reconnect: true

test:
    adapter: postgresql
    host: localhost
    database: pintrest_test
    username: postgres
    password: cuelinks
    reconnect: true

production:
    adapter: postgresql
    database: pintrest_production
    username: postgres
    password: cuelinks
    reconnect: true
staging:
    adapter: postgresql
    database: pintrest_staging
    username: postgres
    password: cuelinks
    reconnect: true
